import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Marck_Script,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import HeartsRain from "../utils/heart/Heart";
import HeartEffect from "../utils/heartTouch/HeartTouch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
});
const playfair = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600"],
});
const marck = Marck_Script({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} ${marck.className} ${playfair.className} antialiased`}
      >
        <HeartsRain />
        <HeartEffect />
        {children}
      </body>
    </html>
  );
}
